/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/data/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_data_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Now */
        post: operations["sync_now_api_data_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/quality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quality */
        get: operations["quality_api_data_quality_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current */
        get: operations["current_api_jobs_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signals */
        get: operations["signals_api_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Instruments */
        get: operations["instruments_api_instruments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/{code}/bars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Bars
         * @description Defaults: up to the latest session, a year back.
         */
        get: operations["bars_api_instruments__code__bars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Strategies
         * @description Each strategy's parameters with their defaults, for the new-account page.
         */
        get: operations["strategies_api_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accounts */
        get: operations["accounts_api_accounts_get"];
        put?: never;
        /**
         * Create
         * @description Creates the account and queues its backtest at once (spec §8).
         */
        post: operations["create_api_accounts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_accounts__account_id__get"];
        put?: never;
        post?: never;
        /** Delete */
        delete: operations["delete_api_accounts__account_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}/nav": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nav
         * @description The net asset value and TOPIX, both from 1 on the first session, and
         *     how far the NAV stands below its highest so far.
         */
        get: operations["nav_api_accounts__account_id__nav_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Orders
         * @description The orders and account events so far, newest first; tomorrow's orders
         *     are on the account itself, as `pending`.
         */
        get: operations["orders_api_accounts__account_id__orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop */
        post: operations["stop_api_accounts__account_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sources */
        get: operations["sources_api_research_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History */
        get: operations["history_api_research_runs_get"];
        put?: never;
        /** Submit */
        post: operations["submit_api_research_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_api_research_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/runs/{run_id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Orders */
        get: operations["orders_api_research_runs__run_id__orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/research/runs/{run_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_api_research_runs__run_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountCreated */
        AccountCreated: {
            /** Id */
            id: number;
            /** Advance Job Id */
            advance_job_id: string | null;
            /** Advance Refused */
            advance_refused: string | null;
        };
        /** AccountDetailOut */
        AccountDetailOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Strategy */
            strategy: string;
            /** Strategy Params */
            strategy_params: {
                [key: string]: unknown;
            };
            /** Rules */
            rules: {
                [key: string]: number;
            };
            /** Costs */
            costs: {
                [key: string]: number;
            };
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Advanced Through */
            advanced_through: string | null;
            /** Status */
            status: string;
            /** Backtest Data Mark */
            backtest_data_mark: {
                [key: string]: unknown;
            } | null;
            figures: components["schemas"]["FiguresOut"] | null;
            /** Holdings */
            holdings: components["schemas"]["HoldingOut"][];
            /** Pending */
            pending: components["schemas"]["OrderOut"][];
        };
        /**
         * AccountIn
         * @description A new account (spec §3.5); anything left out takes its default.
         */
        AccountIn: {
            /** Name */
            name: string;
            /** Strategy */
            strategy: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * Strategy Params
             * @default {}
             */
            strategy_params: {
                [key: string]: unknown;
            };
            /**
             * Initial Cash
             * @default 10000000
             */
            initial_cash: number;
            /**
             * Max Positions
             * @default 10
             */
            max_positions: number;
            /**
             * Max Weight
             * @default 0.1
             */
            max_weight: number;
            /**
             * Cash Floor
             * @default 0.05
             */
            cash_floor: number;
            /**
             * Commission Rate
             * @default 0
             */
            commission_rate: number;
            /**
             * Commission Min
             * @default 0
             */
            commission_min: number;
            /**
             * Slippage
             * @default 0.001
             */
            slippage: number;
        };
        /** AccountSummaryOut */
        AccountSummaryOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Strategy */
            strategy: string;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Advanced Through */
            advanced_through: string | null;
            /** Status */
            status: string;
            /** Total Return */
            total_return: number | null;
            /** Annualised Return */
            annualised_return: number | null;
            /** Max Drawdown */
            max_drawdown: number | null;
            /** Excess Annualised Return */
            excess_annualised_return: number | null;
        };
        /**
         * BarOut
         * @description Research prices: comparable across splits. None on a halted day.
         */
        BarOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Open */
            open: number | null;
            /** High */
            high: number | null;
            /** Low */
            low: number | null;
            /** Close */
            close: number | null;
            /** Volume */
            volume: number | null;
        };
        /** CandidateOut */
        CandidateOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Market */
            market: string | null;
            /** Priority */
            priority: number | null;
            /** Reason Codes */
            reason_codes: string[];
        };
        /** DataQuality */
        DataQuality: {
            /** Missing Sessions */
            missing_sessions: string[];
            /** Gaps */
            gaps: components["schemas"]["SecurityGap"][];
            /** Untradable Rows */
            untradable_rows: number;
            /** Untradable On Latest */
            untradable_on_latest: number;
        };
        /** DataStatus */
        DataStatus: {
            /** Latest Date */
            latest_date: string | null;
            /** Securities */
            securities: number;
            /** Bar Rows */
            bar_rows: number;
            /** Recent Jobs */
            recent_jobs: components["schemas"]["JobResultOut"][];
        };
        /**
         * FiguresOut
         * @description Spec §7.4. Dividends and tax are not included.
         */
        FiguresOut: {
            /** Total Return */
            total_return: number;
            /** Annualised Return */
            annualised_return: number | null;
            /** Max Drawdown */
            max_drawdown: number;
            /** Sharpe */
            sharpe: number | null;
            /** Win Rate */
            win_rate: number | null;
            /** Closed Positions */
            closed_positions: number;
            /** Average Holding Sessions */
            average_holding_sessions: number | null;
            /** Annual Turnover */
            annual_turnover: number | null;
            /** Excess Annualised Return */
            excess_annualised_return: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HoldingOut */
        HoldingOut: {
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            /** Quantity */
            quantity: number;
            /**
             * Opened On
             * Format: date
             */
            opened_on: string;
            /** Cost */
            cost: number;
            /** Close */
            close: number;
            /** Value */
            value: number;
        };
        /** InstrumentOut */
        InstrumentOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Name En */
            name_en: string;
            /** Market */
            market: string | null;
        };
        /** JobResultOut */
        JobResultOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at: string;
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
            /** Warnings */
            warnings: string[];
            /** Error */
            error: string | null;
        };
        /** JobStatusOut */
        JobStatusOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** State */
            state: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Started At */
            started_at: string | null;
            /** Progress */
            progress: {
                [key: string]: unknown;
            } | null;
        };
        /** LinePoint */
        LinePoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Value */
            value: number | null;
        };
        /** NavPointOut */
        NavPointOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Nav */
            nav: number;
            /** Nav Curve */
            nav_curve: number;
            /** Topix Curve */
            topix_curve: number;
            /** Drawdown */
            drawdown: number;
        };
        /**
         * OrderOut
         * @description An order or an account event (spec §3.6).
         */
        OrderOut: {
            /** Id */
            id: number | null;
            /** Kind */
            kind: string;
            /** Code */
            code: string;
            /** Name */
            name: string | null;
            /**
             * Signal Date
             * Format: date
             */
            signal_date: string;
            /**
             * Execution Date
             * Format: date
             */
            execution_date: string;
            /** Planned Quantity */
            planned_quantity: number;
            /** Priority */
            priority: number | null;
            /** Reason */
            reason: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
            /** Outcome Reason */
            outcome_reason: string | null;
            /** Filled Quantity */
            filled_quantity: number;
            /** Fill Price */
            fill_price: number | null;
            /** Fees */
            fees: number;
            /** Cash Delta */
            cash_delta: number;
        };
        /**
         * OrdersPageOut
         * @description One page of an account's history, newest first. The groups do not
         *     overlap: a skipped order counts as skipped, not as a buy or a sell.
         */
        OrdersPageOut: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /** Orders */
            orders: components["schemas"]["OrderOut"][];
        };
        /** PlotOut */
        PlotOut: {
            /** Indicator */
            indicator: string;
            /** Pane */
            pane: string;
        };
        /**
         * Refusal
         * @description Why a request was turned away (FastAPI's `HTTPException` shape).
         */
        Refusal: {
            /** Detail */
            detail: string;
        };
        /** ResearchAccepted */
        ResearchAccepted: {
            /** Id */
            id: string;
        };
        /** ResearchConfig */
        ResearchConfig: {
            /** Name */
            name: string;
            /** Strategy */
            strategy: string;
            /** Strategy Params */
            strategy_params: {
                [key: string]: unknown;
            };
            /** Portfolio Rules */
            portfolio_rules: {
                [key: string]: unknown;
            };
            /** Costs */
            costs: {
                [key: string]: string;
            };
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date?: string | null;
            /** Source Account Id */
            source_account_id?: number | null;
        };
        /** ResearchDetail */
        ResearchDetail: {
            /** Id */
            id: string;
            config: components["schemas"]["ResearchConfig"];
            /** Retry Of */
            retry_of: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed";
            /** Created At */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Progress */
            progress: {
                [key: string]: unknown;
            };
            /** Input Identity */
            input_identity: {
                [key: string]: unknown;
            } | null;
            /** Code Version */
            code_version: string;
            /** Error */
            error: string | null;
            result: components["schemas"]["ResearchResult"] | null;
        };
        /** ResearchHistory */
        ResearchHistory: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Runs */
            runs: components["schemas"]["ResearchSummary"][];
        };
        /** ResearchHolding */
        ResearchHolding: {
            /** Code */
            code: string;
            /** Quantity */
            quantity: number;
            /**
             * Opened On
             * Format: date
             */
            opened_on: string;
            /** Cost */
            cost: number;
            /** Close */
            close: number;
            /** Value */
            value: number;
        };
        /** ResearchIn */
        ResearchIn: {
            /**
             * Request Key
             * Format: uuid
             */
            request_key: string;
            /** Source Account Id */
            source_account_id: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /**
             * End Date
             * Format: date
             */
            end_date: string;
            /**
             * Entry Above
             * @default 0.5
             */
            entry_above: number;
            /**
             * Exit Below
             * @default -0.1
             */
            exit_below: number;
        };
        /** ResearchOrders */
        ResearchOrders: {
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Orders */
            orders: components["schemas"]["OrderOut"][];
        };
        /** ResearchResult */
        ResearchResult: {
            /** Nav */
            nav: components["schemas"]["NavPointOut"][];
            /** Holdings */
            holdings: components["schemas"]["ResearchHolding"][];
            /** Pending */
            pending: components["schemas"]["OrderOut"][];
            /** Warnings */
            warnings: string[];
            /** Total Return */
            total_return: number;
            /** Topix Return */
            topix_return: number;
            /** Excess Return */
            excess_return: number;
            /** Max Drawdown */
            max_drawdown: number;
            /** Trades */
            trades: number;
            /** Fees */
            fees: number;
            /** Cash */
            cash: number;
            /** Realised Pnl */
            realised_pnl: number;
            /** Unrealised Pnl */
            unrealised_pnl: number;
        };
        /** ResearchRetryIn */
        ResearchRetryIn: {
            /**
             * Request Key
             * Format: uuid
             */
            request_key: string;
        };
        /** ResearchSource */
        ResearchSource: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            config: components["schemas"]["ResearchConfig"];
        };
        /** ResearchSummary */
        ResearchSummary: {
            /** Id */
            id: string;
            config: components["schemas"]["ResearchConfig"];
            /** Retry Of */
            retry_of: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed";
            /** Created At */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Progress */
            progress: {
                [key: string]: unknown;
            };
            /** Input Identity */
            input_identity: {
                [key: string]: unknown;
            } | null;
            /** Code Version */
            code_version: string;
            /** Error */
            error: string | null;
        };
        /** SecurityBarsOut */
        SecurityBarsOut: {
            /** Code */
            code: string;
            /** Bars */
            bars: components["schemas"]["BarOut"][];
            /** Plots */
            plots: components["schemas"]["PlotOut"][];
            /** Lines */
            lines: {
                [key: string]: components["schemas"]["LinePoint"][];
            };
            /** Entries */
            entries: string[];
        };
        /** SecurityGap */
        SecurityGap: {
            /** Code */
            code: string;
            /** Missing Sessions */
            missing_sessions: number;
        };
        /** SignalsOut */
        SignalsOut: {
            /** Strategy */
            strategy: string;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Candidates */
            candidates: components["schemas"]["CandidateOut"][];
        };
        /** StrategyOut */
        StrategyOut: {
            /** Name */
            name: string;
            /** Defaults */
            defaults: {
                [key: string]: unknown;
            };
        };
        /** SyncAccepted */
        SyncAccepted: {
            /** Job Id */
            job_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    status_api_data_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataStatus"];
                };
            };
        };
    };
    sync_now_api_data_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncAccepted"];
                };
            };
            /** @description 已有任务正在运行，没有排入 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    quality_api_data_quality_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataQuality"];
                };
            };
        };
    };
    current_api_jobs_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusOut"] | null;
                };
            };
        };
    };
    signals_api_signals_get: {
        parameters: {
            query: {
                strategy: string;
                date?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalsOut"];
                };
            };
            /** @description 没有这个策略，或还没有行情 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    instruments_api_instruments_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bars_api_instruments__code__bars_get: {
        parameters: {
            query: {
                strategy: string;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityBarsOut"];
                };
            };
            /** @description 没有这个策略，或还没有行情 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    strategies_api_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyOut"][];
                };
            };
        };
    };
    accounts_api_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountSummaryOut"][];
                };
            };
        };
    };
    create_api_accounts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountCreated"];
                };
            };
            /** @description 参数不合规 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    detail_api_accounts__account_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDetailOut"];
                };
            };
            /** @description 没有这个账户 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_api_accounts__account_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 没有这个账户 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    nav_api_accounts__account_id__nav_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NavPointOut"][];
                };
            };
            /** @description 没有这个账户 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    orders_api_accounts__account_id__orders_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                kind?: "all" | "buy" | "sell" | "skipped" | "events";
            };
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrdersPageOut"];
                };
            };
            /** @description 没有这个账户 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_api_accounts__account_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 没有这个账户 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sources_api_research_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchSource"][];
                };
            };
        };
    };
    history_api_research_runs_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchHistory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_api_research_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchAccepted"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    detail_api_research_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchDetail"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    orders_api_research_runs__run_id__orders_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchOrders"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
    retry_api_research_runs__run_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResearchRetryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchAccepted"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Refusal"];
                };
            };
        };
    };
}
